version: '3'

volumes:
  pg_data_kittygram_production:
  static_volume:
  media:

services:
  db_kittygram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_kittygram_production:/var/lib/postgresql/data
  
  backend:
    image: sergeykataev1/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media
    depends_on:
      - db_kittygram

  frontend:
    image: sergeykataev1/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  
  gateway:
    image: sergeykataev1/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static
      - media:/media
    ports:
      - 9000:80