version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: sergeykataev1/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/

  frontend:
    image: sergeykataev1/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles/
  
  gateway:
    image: sergeykataev1/kittygram_gateway
    volumes:
      - static:/app/static/
      - media:/app/media/
    ports:
      - 9000:80
